### ISSUE TITLE
CurveEditors and Class editors changes all values

### ISSUE THREAD

**Issue by CaptRobau** [ThomasKerman/KittopiaTech#1]
When I use the 1.0.4 KT with 1.0.5 Kopernicus, then whenever I edit a Class, it's impossible to change the numbers properly. In a loaded from CFG HeightColorMap, I have three classes. Whenever I change one of them, all three the classes take those values.

Related to this could be that when I edit the HazardousOcean curve in KT, the entire row changes with it. So if I put 5 in the first cell, it'll become 5 5 5 5. I don't know HazardousOcean well enough to say that it's not WAD, but it could also be a bug.

**Comment by Sigma88** [comment]
I am seeing the same issues
it also affects position "vectors" for mods that require a position (PQSCity, Mapdecals, etc)
and I believe it fails for LandControl classes and VertexPlanet classes as well

**Comment by StollD** [comment]
I said "It _should_ fix.." Github.

**Comment by StollD** [comment]
I think this is fixed
