### ISSUE TITLE
Stars do not export

### ISSUE THREAD

**Issue by Sigma88** [ThomasKerman/KittopiaTech#2]
Here's a list of stock planets that cannot be exported, and the workaround I used to export them.

Attached there also is an output.log from a session in which I tried to export stock planets (without any workaround)

[kopernicus-wont-export-most-of-the-stock-planets---output_log.txt](https://github.com/Kopernicus/KittopiaTech/files/572291/kopernicus-wont-export-most-of-the-stock-planets---output_log.txt)

|  Planet | Exports | Workaround |
|:-------------:|:-------------:|:-----------|
| Sun                | No                |  None at the moment     |
| Moho                | No                | Remove PQSCity[Mohole] using kittopia |
| Eve                | No                | add *removeOcean = true* in the cfg |
| Gilly                | Yes                | --- |
| Kerbin                | No                | add *removeOcean = true* in the cfg |
| Mun                | Yes                | --- |
| Minmus                 | Yes                | --- |
| Duna                | No                | Remove PQSCity[Pyramids] using kittopia |
| Ike                | Yes                | --- |
| Dres                | Yes                | --- |
| Jool                | Yes                | --- |
| Laythe                | No                | add *removeOcean = true* in the cfg |
| Vall                | No                | Remove PQSCity[Icehenge] using kittopia |
| Tylo                | Yes                | --- |
| Bop                | No                | Remove PQSCity[DeadKraken] using kittopia |
| Pol                | Yes                | --- |
| Eeloo                | Yes                | --- |

**Comment by StollD** [comment]
Seems that I have to block PQSCity from getting exportet

**Comment by Sigma88** [comment]
all planets can be exported now, but the sun still cannot

**Comment by Sigma88** [comment]
here are the logs

[output_log.txt](https://github.com/Kopernicus/KittopiaTech/files/1034591/output_log.txt)

these logs are generated on a stock install (1.3.0 + latest kopernicus + latest kittopia)

I try to export the sun and a custom star I created using this cfg

[test.cfg.txt](https://github.com/Kopernicus/KittopiaTech/files/1034590/test.cfg.txt)


both stars failed to export

**Comment by Sigma88** [comment]
old issue
